### ISSUE TITLE
I tested your code, it worked Will there be result code for live video and Reenactment?

### ISSUE THREAD

**Issue by D-Mad** [mbzuai-metaverse/VOODOO3D-official#7]
I tested your code, it worked
Will there be result code for live video and Reenactment?

![image](https://github.com/mbzuai-metaverse/VOODOO3D-official/assets/8207507/8cd34ef2-a35e-460e-a231-435c289be68f)

**Comment by P0lyFish** [comment]
Hi,

We currently do not have plans to release the real-time demo code. The demo involves significant engineering work and is tailored to specific hardware, making it challenging to support and less relevant from an academic standpoint.

To achieve real-time performance, we utilized FP16 and TensorRT optimization, along with extensive optimizations in the data preprocessing part.
