### ISSUE TITLE
Explicitly passing `rgb2bgr=False` needed?

### ISSUE THREAD

**Issue by yakhyo** [mbzuai-metaverse/VOODOO3D-official#9]
Thanks for your work, I noticed while running `test_voodoo3d.py` with default configs the generated output is in BGR format.

https://github.com/mbzuai-metaverse/VOODOO3D-official/blob/89dd2bea888e91ed7e62bac8d0a53c927b071f92/test_voodoo3d.py#L109-L112

To resolve this, the code needs to be changed to following,  adding `rgb2bgr=True` param -> 
```python
out_hr = tensor2img(out['image'], rgb2bgr=False, min_max=(-1, 1))

source_img = tensor2img(source_data['image'][0], rgb2bgr=False, min_max=(-1, 1))
driver_img = tensor2img(driver_data['image'][0], rgb2bgr=False, min_max=(-1, 1))
```

**Comment by P0lyFish** [comment]
It's depend on what are you going to do with the output. In my sample code, I saved the images using cv2 which requires BGR order format.

**Comment by yakhyo** [comment]
Well, below you can see the difference. Or is it intended behavior?

With default model output:
![image](https://github.com/mbzuai-metaverse/VOODOO3D-official/assets/28424328/6da0c615-28b3-40ab-b472-46447123f5ca)

Adding `rgb2bgr=False` to `tensor2img` function:
![image](https://github.com/mbzuai-metaverse/VOODOO3D-official/assets/28424328/153b9c84-d04f-44a3-9579-86d692b09c00)

**Comment by JZArray** [comment]
> It's depend on what are you going to do with the output. In my sample code, I saved the images using cv2 which requires BGR order format.

@P0lyFish Could you release codes for MegaPortraits? I have opened one issue to ask this question, why you ignore it? You said you would release these codes in another issue.
